### ISSUE TITLE
你好，咨询下，现在这个repo 能够生成markdown文件吗

### ISSUE THREAD

**Issue by veaba** [yiidot/tsdoc2md-demo#3]
我clone 这个demo尝试跑下，似乎不怎么成功。

并没有自动生成`markdown`文件让`vuepress`去渲染。

现在仓库中，似乎是`vuepress` 和 `tsdoc2md` 没有直接关系。

不知道是不是我的姿势错了~

期待开发者予以解惑，谢谢。~~

**Comment by yiidot** [comment]
这个demo是用于测试tsdoc2md生成的markdown文件，生成markdown是使用[tsdoc2md](https://www.npmjs.com/package/tsdoc2md)。

**Comment by yiidot** [comment]
不好意思，我刚刚运行了一遍这个demo，是没问题的，可能是依赖的版本比较旧，我用了yarn去安装依赖。

**Comment by yiidot** [comment]
@veaba 不好意思，我刚刚运行了一遍这个demo，是没问题的，可能是依赖的版本比较旧，我用了yarn去安装依赖。

**Comment by veaba** [comment]
@yiidot hi，没关系的，这是早些时候可能尝试过 ts doc 转 md 的操作，找到的demo。

非常感谢你的回复，我后续研究研究

:+1:
